image: docker:stable
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  REPO_PATH: "/home/deploy/DomainAccessibilityAudit"
  CONNECT: "deploy@da11y.lib.msu.edu"


build:
  stage: build
  tags:
    - msul
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

deploy:
  stage: deploy
  environment:
    name: prod
    url: "https://da11y.lib.msu.edu"
  tags:
    - msul
  only:
    - master
  when: manual
  script:
    - ssh $CONNECT git -C $REPO_PATH reset HEAD --hard
    - ssh $CONNECT git -C $REPO_PATH fetch gitlab
    - ssh $CONNECT git -C $REPO_PATH checkout $CI_COMMIT_SHORT_SHA
    - ssh $CONNECT "sed -i 's|^\( *\)accessibility_audit:$|&\n\1  image:\ registry.gitlab.msu.edu\/msu-libraries\/devops\/domainaccessibilityaudit:$CI_COMMIT_SHORT_SHA|' $REPO_PATH/docker-compose.yml"
    - ssh $CONNECT docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ssh $CONNECT "(cd $REPO_PATH && docker-compose -f $REPO_PATH/docker-compose.yml config)"
    - ssh $CONNECT "(cd $REPO_PATH && docker-compose -f $REPO_PATH/docker-compose.yml pull)"
    - ssh $CONNECT sudo /bin/systemctl restart daa
    - sleep 30
    - ssh $CONNECT sudo /bin/systemctl status daa
    - ssh $CONNECT docker container prune -f
    - ssh $CONNECT docker image prune -f -a
    - ssh $CONNECT "[[ $( curl -s -o /dev/null -k -I -w \"%{http_code}\" $CI_ENVIRONMENT_URL ) -eq 200 ]]"

